logging:
  level:
    org:
      qnit: debug
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pbs_admin?useSSL=false&useUnicode=yes&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 3
      idle-timeout: 1800000
      max-lifetime: 1800000
      maximum-pool-size: 15
  redis:
    dbIndex: 0
    host: 127.0.0.1
    hostName: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    poolConfig:
      maxActive: 50
      minIdle: 3
      maxIdle: 15
      maxWait: 30000
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  aop:
    proxy-target-class: true
    auto: true
  devtools:
    restart:
      enabled: true  #设置开启热部署
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/*/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/**.xml
  mapper-locations: classpath:/mapper/**.xml
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 8081
oss:
  project_name: 'pbs-system'
  upload_file_path: 'E:/pbsstore'
  file: sh
## 定时任务
schedule:
  ## 线程池配置
  thread:
    corePoolSize: 10
    maxPoolSize: 200
    queueCapacity:  10
  time:
    cron: 0 54 0 * * ?